Fix assertion error
imgui.core.ImGuiError: ImGui assertion error (g.IO.KeyMap[ImGuiKey_Space] != -1 && "ImGuiKey_Space is not mapped, required for keyboard navigation.") at imgui-cpp/imgui.cpp:3101

Error was thrown after enabling keyboard navigation because of the missing 'space' key in REVERSE_KEY_MAP